# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CIFAR10": "00_data.cifar.ipynb",
         "CIFAR10DataModule": "00_data.cifar.ipynb",
         "DummyModel": "01_model.dummy.ipynb",
         "ModuleName": "template_nb.ipynb"}

modules = ["data/cifar.py",
           "model/dummy.py",
           "module/template.py"]

doc_url = "https://fastai.github.io/nbs_template/"

git_url = "https://github.com/fastai/nbs_template/tree/master/"

def custom_doc_links(name): return None
